version: "1.0"

services:
    worktracker-database:
        image: mysql:8.0.33
        environment:
            MYSQL_ROOT_PASSWORD: StRoNg_PaSsWoRd
            MYSQL_DATABASE: worktracker
            MYSQL_USER: user
            MYSQL_PASSWORD: uSeRpAsSwOrD
        ports:
            - "3306:3306"
        container_name: worktracker-database
        networks:
            - worktracker-network
    worktracker-api:
        build:
          context: ../../src/
          dockerfile: Dockerfile
        ports:
            - "3000:80"
        environment:
            ConnectionStrings__DefaultConnection: "Server=worktracker-database;Port=3306;Database=worktracker;Uid=user;Pwd=uSeRpAsSwOrD"
            Cognito__Authority: "{{ COGNITO_AUTHORITY }}"
            Cognito__ClientId: "{{ COGNITO_CLIENT_ID }}"
            Cognito__IdpUrl: "{{ COGNITO_IDPURL }}"
            Mailtrap__Username: "{{ MAILTRAP_USERNAME }}"
            Mailtrap__Password: "{{ MAILTRAP_PASSWORD }}"
            Mailtrap__Host: "{{ MAILTRAP_HOST }}"
            AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
            AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
            AWS_SESSION_TOKEN: "{{ AWS_SESSION_TOKEN }}"
        depends_on:
            - worktracker-database
        networks:
            - worktracker-network
        restart: always
networks:
    worktracker-network:
        driver: bridge

    
    